In [13]:
import numpy as np

def wedge_1form_2form(one_form, two_form):
    """
    Compute the wedge product of a 1-form and a 2-form numerically.
    one_form: shape (n,) – coefficients of 1-form
    two_form: shape (n, n) – antisymmetric matrix of 2-form
    Returns:
        A rank-3 antisymmetric tensor: shape (n, n, n)
    """
    n = one_form.shape[0]
    result = np.zeros((n, n, n))
    for i in range(n):
        for j in range(n):
            for k in range(n):
                result[i, j, k] = (
                    one_form[i] * two_form[j, k]
                    - one_form[j] * two_form[i, k]
                    + one_form[k] * two_form[i, j]
                )
    return result
one_form = np.array([1, 2, 3])
two_form = np.array([
    [ 0,  1,  2],
    [-1,  0,  3],
    [-2, -3,  0]
])

wedge_result = wedge_1form_2form(one_form, two_form)

print(np.round(wedge_result).astype(int))

[[[ 0  0  0]
  [ 0  0  2]
  [ 0 -2  0]]

 [[ 0  0 -2]
  [ 0  0  0]
  [ 2  0  0]]

 [[ 0  2  0]
  [-2  0  0]
  [ 0  0  0]]]


In [105]:
import numpy as np
from itertools import permutations
from math import factorial

def sign_of_permutation(p):
    """Return the sign (+1 or -1) of a permutation."""
    inversions = 0
    p = list(p)
    for i in range(len(p)):
        for j in range(i+1, len(p)):
            if p[i] > p[j]:
                inversions += 1
    return (-1)**inversions

def wedge_product(A, B):
    """
    Wedge product A ∧ B of antisymmetric tensors A (rank p) and B (rank q).
    A shape: (n,)*p
    B shape: (n,)*q
    Output shape: (n,)*(p+q)
    """
    p = A.ndim
    q = B.ndim
    n = A.shape[0]

    # Full tensor product (no contraction)
    tensor_prod = np.tensordot(A, B, axes=0)  # shape: (n,)*p + (n,)*q
    tensor_prod = tensor_prod.reshape((n,) * (p + q))

    # Antisymmetrize over all indices
    result = np.zeros_like(tensor_prod, dtype=np.float64)
    for perm in set(permutations(range(p + q))):
        sign = sign_of_permutation(perm)
        permuted = np.transpose(tensor_prod, perm)
        result += sign * permuted
    # result /= factorial(p + q)
    return result

a = np.array([1, 2, 3])  # 1-form
b = np.array([4,5,6])  # 2-form

wedge_ab = wedge_product(a, b)
print(np.round(wedge_ab).astype(int))  # shape (3,3,3)

[[ 0 -3 -6]
 [ 3  0 -3]
 [ 6  3  0]]


In [78]:
phi = np.array([[[ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ],
        [ 0.   ,  0.   ,  0.008,  0.   ,  0.   ,  0.095,  0.   ],
        [ 0.   , -0.008,  0.   ,  0.   ,  0.095,  0.   ,  0.021],
        [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ],
        [ 0.   ,  0.   , -0.095,  0.   ,  0.   , -0.008,  0.078],
        [ 0.   , -0.095,  0.   ,  0.   ,  0.008,  0.   ,  0.008],
        [ 0.   ,  0.   , -0.021,  0.   , -0.078, -0.008,  0.   ]],

       [[ 0.   ,  0.   , -0.008,  0.   ,  0.   , -0.095,  0.   ],
        [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ],
        [ 0.008,  0.   ,  0.   ,  0.095,  0.   ,  0.   , -0.03 ],
        [ 0.   ,  0.   , -0.095,  0.   ,  0.   , -0.008,  0.   ],
        [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.008],
        [ 0.095,  0.   ,  0.   ,  0.008,  0.   ,  0.   ,  0.121],
        [ 0.   ,  0.   ,  0.03 ,  0.   , -0.008, -0.121,  0.   ]],

       [[ 0.   , -0.008,  0.   ,  0.   , -0.095,  0.   , -0.021],
        [-0.008,  0.   ,  0.   , -0.095,  0.   ,  0.   ,  0.03 ],
        [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ],
        [ 0.   ,  0.095,  0.   ,  0.   , -0.008,  0.   , -0.102],
        [ 0.095,  0.   ,  0.   ,  0.008,  0.   ,  0.   ,  0.   ],
        [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ],
        [ 0.021, -0.03 ,  0.   ,  0.102,  0.   ,  0.   ,  0.   ]],

       [[ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ],
        [ 0.   ,  0.   , -0.095,  0.   ,  0.   ,  0.008,  0.   ],
        [ 0.   , -0.095,  0.   ,  0.   ,  0.008,  0.   ,  0.102],
        [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ],
        [ 0.   ,  0.   , -0.008,  0.   ,  0.   , -0.095,  0.021],
        [ 0.   , -0.008,  0.   ,  0.   ,  0.095,  0.   , -0.03 ],
        [ 0.   ,  0.   , -0.102,  0.   , -0.021,  0.03 ,  0.   ]],

       [[ 0.   ,  0.   , -0.095,  0.   ,  0.   ,  0.008, -0.078],
        [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   , -0.008],
        [-0.095,  0.   ,  0.   ,  0.008,  0.   ,  0.   ,  0.   ],
        [ 0.   ,  0.   ,  0.008,  0.   ,  0.   ,  0.095, -0.021],
        [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ],
        [-0.008,  0.   ,  0.   , -0.095,  0.   ,  0.   ,  0.   ],
        [ 0.078,  0.008,  0.   ,  0.021,  0.   ,  0.   ,  0.   ]],

       [[ 0.   , -0.095,  0.   ,  0.   ,  0.008,  0.   , -0.008],
        [-0.095,  0.   ,  0.   ,  0.008,  0.   ,  0.   , -0.121],
        [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ],
        [ 0.   ,  0.008,  0.   ,  0.   ,  0.095,  0.   ,  0.03 ],
        [ 0.008,  0.   ,  0.   ,  0.095,  0.   ,  0.   ,  0.   ],
        [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ],
        [ 0.008,  0.121,  0.   , -0.03 ,  0.   ,  0.   ,  0.   ]],

       [[ 0.   ,  0.   ,  0.021,  0.   ,  0.078,  0.008,  0.   ],
        [ 0.   ,  0.   , -0.03 ,  0.   ,  0.008,  0.121,  0.   ],
        [-0.021,  0.03 ,  0.   , -0.102,  0.   ,  0.   ,  0.   ],
        [ 0.   ,  0.   ,  0.102,  0.   ,  0.021, -0.03 ,  0.   ],
        [-0.078, -0.008,  0.   , -0.021,  0.   ,  0.   ,  0.   ],
        [-0.008, -0.121,  0.   ,  0.03 ,  0.   ,  0.   ,  0.   ],
        [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ]]])

In [115]:
import numpy as np
from itertools import combinations
from joblib import Parallel, delayed

# Assuming G2_val and phi are defined globally or passed in
def process_pair(i, j, phi):
    B1 = np.zeros((7, 7))
    B2 = np.zeros((7, 7))

    for comb in combinations(range(7), 3):
        a, b, c = comb
        T = [a, b, c]

        if i in T:
            pos = T.index(i)
            ids = T[:pos] + T[pos+1:]
            sign = (-1) ** pos
            B1[ids[0], ids[1]] += sign * phi[a, b, c]

        if j in T:
            pos = T.index(j)
            ids = T[:pos] + T[pos+1:]
            sign = (-1) ** pos
            B2[ids[0], ids[1]] += sign * phi[a, b, c]

    wedge = wedge_product(B2, phi)
    result = wedge_product(B1, wedge)
    return (i, j, result[0, 1, 2, 3, 4, 5, 6])

# Run in parallel
def compute_gG2_parallel(G2_val):
    B = np.zeros((7, 7))

    results = Parallel(n_jobs=-1)(  # -1 uses all available CPUs
        delayed(process_pair)(i, j, G2_val) for i, j in combinations(range(7), 2)
    )

    for i, j, val in results:
        B[i, j] = val

    B = B + B.T - np.diag(np.diag(B))
    
    gG2 = np.zeros((7, 7))
    detB = np.linalg.det(B)
    factor = (1 / pow(36, 2 / 9)) * (1 / pow(detB, 1 / 9))
    gG2 = factor * B
    
    return np.around(gG2, decimals=12)

In [111]:
import numpy as np
from itertools import permutations, combinations
from math import pow

def compute_gG2(G2_val):
    # def sign_of_permutation(p):
    #     return (-1) ** sum(i < j and p[i] > p[j] for i in range(len(p)) for j in range(i + 1, len(p)))

    B = np.zeros((7, 7))
    gG2 = np.zeros((7, 7))

    for aux in combinations(list(range(7)), 2):
        i, j = aux[0], aux[1]     
        B1 = np.zeros((7, 7))
        B2 = np.zeros((7, 7))

        for comb in combinations(range(7), 3):
            a, b, c = comb[0], comb[1], comb[2]
            # contraction by del/del x_i
            T = [a, b, c]
            if i in T:
                pos = T.index(i)
                ids = T[:pos] + T[pos+1:]
                sign = (-1) ** (pos)
                B1[ids[0], ids[1]] += sign * G2_val[a, b, c]
            
            # contraction by del/del x_j
            if j in T:
                pos = T.index(j)
                ids = T[:pos] + T[pos+1:]
                sign = (-1) ** (pos)
                B2[ids[0], ids[1]] += sign * G2_val[a, b, c]

      
        # (*Construct B_ij by contracting (\del/\del x_i \lrcorner \phi)\wedge(\del/\del x_j \lrcorner \phi)\wedge \phi with the canonical vectors *)
        
        B[i,j] = wedge_product(B1, wedge_product(B2, phi))[0,1,2,3,4,5,6]
        
        
    #Symmetrize B 
    B = B + B.T - np.diag(np.diag(B))
    
    detB = np.linalg.det(B)
    factor = (1 / pow(36, 2 / 9)) * (1 / pow(detB, 1 / 9))
    gG2 = factor * B
    
    return np.around(gG2, decimals=12)

In [112]:
compute_gG2(phi)

array([[ 0.        , -0.33561323, -0.40445697,  0.        , -0.09035741,
         0.21943942,  0.40278147],
       [-0.33561323,  0.        ,  0.52063078, -0.09035741, -0.        ,
        -0.12908201, -0.41210321],
       [-0.40445697,  0.52063078,  0.        , -0.21943942, -0.12908201,
         0.        , -0.58428444],
       [ 0.        , -0.09035741, -0.21943942,  0.        , -0.33561323,
         0.40445697,  0.16373806],
       [-0.09035741, -0.        , -0.12908201, -0.33561323,  0.        ,
         0.52063078,  0.02057234],
       [ 0.21943942, -0.12908201,  0.        ,  0.40445697,  0.52063078,
         0.        ,  0.09474781],
       [ 0.40278147, -0.41210321, -0.58428444,  0.16373806,  0.02057234,
         0.09474781,  0.        ]])

In [113]:
metric = np.array([[ 0.        , -0.33561323, -0.40445697,  0.        , -0.09035741,
         0.21943942,  0.40278147],
       [-0.33561323,  0.        ,  0.52063078, -0.09035741, -0.        ,
        -0.12908201, -0.41210321],
       [-0.40445697,  0.52063078,  0.        , -0.21943942, -0.12908201,
         0.        , -0.58428444],
       [ 0.        , -0.09035741, -0.21943942,  0.        , -0.33561323,
         0.40445697,  0.16373806],
       [-0.09035741, -0.        , -0.12908201, -0.33561323,  0.        ,
         0.52063078,  0.02057234],
       [ 0.21943942, -0.12908201,  0.        ,  0.40445697,  0.52063078,
         0.        ,  0.09474781],
       [ 0.40278147, -0.41210321, -0.58428444,  0.16373806,  0.02057234,
         0.09474781,  0.        ]])

In [116]:
compute_gG2_parallel(phi)

array([[ 0.        , -0.33561323, -0.40445697,  0.        , -0.09035741,
         0.21943942,  0.40278147],
       [-0.33561323,  0.        ,  0.52063078, -0.09035741, -0.        ,
        -0.12908201, -0.41210321],
       [-0.40445697,  0.52063078,  0.        , -0.21943942, -0.12908201,
         0.        , -0.58428444],
       [ 0.        , -0.09035741, -0.21943942,  0.        , -0.33561323,
         0.40445697,  0.16373806],
       [-0.09035741, -0.        , -0.12908201, -0.33561323,  0.        ,
         0.52063078,  0.02057234],
       [ 0.21943942, -0.12908201,  0.        ,  0.40445697,  0.52063078,
         0.        ,  0.09474781],
       [ 0.40278147, -0.41210321, -0.58428444,  0.16373806,  0.02057234,
         0.09474781,  0.        ]])

In [117]:
metri_par = np.array([[ 0.        , -0.33561323, -0.40445697,  0.        , -0.09035741,
         0.21943942,  0.40278147],
       [-0.33561323,  0.        ,  0.52063078, -0.09035741, -0.        ,
        -0.12908201, -0.41210321],
       [-0.40445697,  0.52063078,  0.        , -0.21943942, -0.12908201,
         0.        , -0.58428444],
       [ 0.        , -0.09035741, -0.21943942,  0.        , -0.33561323,
         0.40445697,  0.16373806],
       [-0.09035741, -0.        , -0.12908201, -0.33561323,  0.        ,
         0.52063078,  0.02057234],
       [ 0.21943942, -0.12908201,  0.        ,  0.40445697,  0.52063078,
         0.        ,  0.09474781],
       [ 0.40278147, -0.41210321, -0.58428444,  0.16373806,  0.02057234,
         0.09474781,  0.        ]])

In [120]:
np.sqrt(np.linalg.det(metric))

0.09718937694928347